version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: process-manager-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: process-manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - process-manager-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d process-manager" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: process-manager-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: production
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: process-manager
      TYPEORM_PORT: 5432
      JWT_SECRET_KEY: PROCESS_MANAGER_SECRET
      JWT_EXPIRE: 3600
      HASH_SALT: PROCESS_MANAGER_HASH_SALT
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - process-manager-network

volumes:
  postgres_data:


networks:
  process-manager-network:
    driver: bridge
